using System.Globalization;
using System.Text;

/// <summary>
/// Copies the CIE 1931 2° observer and illuminant D65 tables into data/colour and emits them as C# read-only spans,
/// so colour computation ships with the package and never reads a file.
/// </summary>
internal static class CieEmitter
{
    public static void Emit(string cieDirectory, string repository)
    {
        string observerSource = Path.Combine(cieDirectory, "cie1931_2deg_1nm.csv");
        string illuminantSource = Path.Combine(cieDirectory, "cie_d65_5nm.csv");

        (int firstObserver, int stepObserver, double[][] observer) = ReadCsv(observerSource, 4);
        (int firstIlluminant, int stepIlluminant, double[][] illuminant) = ReadCsv(illuminantSource, 2);

        string dataDirectory = Path.Combine(repository, "data", "colour");
        Directory.CreateDirectory(dataDirectory);
        File.Copy(observerSource, Path.Combine(dataDirectory, "cie1931_2deg_1nm.csv"), overwrite: true);
        File.Copy(illuminantSource, Path.Combine(dataDirectory, "cie_d65_5nm.csv"), overwrite: true);

        StringBuilder b = new();
        b.Append("// <auto-generated>\n");
        b.Append("// Generated by tools/Caustikon.Glasses.Generator --cie from data/colour/*.csv. Do not edit; rerun the generator.\n");
        b.Append("// CIE 1931 2° standard observer at 1 nm and CIE standard illuminant D65 at 5 nm, as published by the CIE;\n");
        b.Append("// copied from the colour-science project's data tables (BSD-3-Clause). See DATA-LICENSE.md.\n");
        b.Append("// </auto-generated>\n\n");
        b.Append("namespace Caustikon.Glasses;\n\n");
        b.Append("internal static class CieTables\n{\n");
        b.Append("    internal const int ObserverFirstNanometers = ").Append(firstObserver).Append(";\n");
        b.Append("    internal const int ObserverStepNanometers = ").Append(stepObserver).Append(";\n");
        b.Append("    internal const int ObserverCount = ").Append(observer.Length).Append(";\n");
        b.Append("    internal const int IlluminantFirstNanometers = ").Append(firstIlluminant).Append(";\n");
        b.Append("    internal const int IlluminantStepNanometers = ").Append(stepIlluminant).Append(";\n");
        b.Append("    internal const int IlluminantCount = ").Append(illuminant.Length).Append(";\n\n");
        AppendSpan(b, "XBar", observer.Select(static r => r[1]));
        AppendSpan(b, "YBar", observer.Select(static r => r[2]));
        AppendSpan(b, "ZBar", observer.Select(static r => r[3]));
        AppendSpan(b, "D65", illuminant.Select(static r => r[1]));
        b.Append("}\n");

        string target = Path.Combine(repository, "src", "Caustikon.Glasses", "Generated", "CieTables.g.cs");
        Directory.CreateDirectory(Path.GetDirectoryName(target)!);
        File.WriteAllText(target, b.ToString(), new UTF8Encoding(false));
        Console.WriteLine($"CIE tables: observer {observer.Length} rows from {firstObserver} nm step {stepObserver}; D65 {illuminant.Length} rows from {firstIlluminant} nm step {stepIlluminant}.");
    }

    private static (int First, int Step, double[][] Rows) ReadCsv(string path, int columns)
    {
        List<double[]> rows = [];
        foreach (string line in File.ReadLines(path).Skip(1))
        {
            if (string.IsNullOrWhiteSpace(line))
            {
                continue;
            }

            string[] fields = line.Split(',');
            if (fields.Length != columns)
            {
                throw new InvalidDataException($"{path}: expected {columns} columns, got {fields.Length}: {line}");
            }

            rows.Add(fields.Select(static f => double.Parse(f, NumberStyles.Float, CultureInfo.InvariantCulture)).ToArray());
        }

        if (rows.Count < 2)
        {
            throw new InvalidDataException($"{path}: fewer than two rows.");
        }

        int first = (int)rows[0][0];
        int step = (int)(rows[1][0] - rows[0][0]);
        for (int i = 0; i < rows.Count; i++)
        {
            if (rows[i][0] != first + i * step)
            {
                throw new InvalidDataException($"{path}: wavelength grid is not uniform at row {i}.");
            }
        }

        return (first, step, [.. rows]);
    }

    private static void AppendSpan(StringBuilder b, string name, IEnumerable<double> values)
    {
        b.Append("    internal static ReadOnlySpan<double> ").Append(name).Append(" =>\n    [\n");
        int column = 0;
        b.Append("        ");
        foreach (double value in values)
        {
            if (column == 6)
            {
                b.Append('\n').Append("        ");
                column = 0;
            }

            b.Append(value.ToString("R", CultureInfo.InvariantCulture)).Append("d, ");
            column++;
        }

        b.Append("\n    ];\n\n");
    }
}
