namespace Caustikon.Site.Localization;

/// <summary>Every piece of site text in English and Russian, keyed by page and role. Numbers, code and formulas stay as they are.</summary>
public static class Strings
{
    static Strings()
    {
        foreach ((string key, (string, string) pair) in GiveStrings.Table)
        {
            Table[key] = pair;
        }
    }

    public static readonly Dictionary<string, (string En, string Ru)> Table = new(StringComparer.Ordinal)
    {
        // Layout
        ["nav.catalog"] = ("Catalog", "Catalog"),
        ["nav.playground"] = ("Slab and interface calculator", "Калькулятор пластины и границы"),
        ["nav.render"] = ("3D", "3D"),
        ["nav.use"] = ("Design", "Design"),
        ["nav.bench"] = ("Optic", "Optic"),
        ["nav.guides"] = ("Guides", "Гайды"),
        ["footer.by"] = ("Made by", "Автор:"),
        ["nav.formulas"] = ("Formulas", "Формулы"),
        ["nav.about"] = ("About", "О проекте"),
        ["footer.data"] = ("Glass data: RefractiveIndex.INFO, CC0 1.0", "Данные стёкол: RefractiveIndex.INFO, CC0 1.0"),
        ["footer.glasses"] = ("glasses", "стёкол"),
        ["footer.vendors"] = ("manufacturers", "производителей"),
        ["footer.colour"] = ("Colour: CIE 1931 2°, D65", "Цвет: CIE 1931 2°, D65"),
        ["notfound.title"] = ("No page here", "Такой страницы нет"),
        ["notfound.text"] = ("The address does not match a page of this site. <a href=\"\">Start over</a> or open the <a href=\"catalog\">catalog</a>.", "Адрес не соответствует ни одной странице. <a href=\"\">На главную</a> или в <a href=\"catalog\">каталог</a>."),

        // Home
        ["home.title"] = ("Caustikon", "Caustikon"),
        ["home.h1"] = ("Geometric optics for .NET, with the glass included", "Геометрическая оптика для .NET, вместе со стеклом"),
        ["home.lede"] = ("Refraction, exact Fresnel reflectance and dispersion as allocation-free value types, and a catalog of {0} manufacturer glasses with dispersion, absorption and temperature data, each number cited.",
            "Преломление, точные коэффициенты Френеля и дисперсия как значимые типы без аллокаций, и каталог из {0} стёкол производителей с дисперсией, поглощением и температурными данными — у каждого числа есть источник."),
        ["home.bench.glass"] = ("Glass", "Стекло"),
        ["home.bench.shape"] = ("Shape", "Форма"),
        ["home.shape.polygon"] = ("regular polygon", "правильный многоугольник"),
        ["home.shape.lens"] = ("biconvex lens", "двояковыпуклая линза"),
        ["home.shape.plate"] = ("tilted plate", "наклонная пластина"),
        ["home.bench.corners"] = ("Corners", "Углов"),
        ["home.bench.angle"] = ("Beam angle", "Угол луча"),
        ["home.bench.height"] = ("Beam height", "Высота луча"),
        ["home.bench.drag"] = ("drag the corners", "таскать углы"),
        ["home.bench.add"] = ("Add a corner", "Добавить угол"),
        ["home.bench.remove"] = ("Remove one", "Убрать один"),
        ["home.bench.reset"] = ("Reset", "Сбросить"),
        ["home.readout.min"] = ("smallest deviation", "наименьшее отклонение"),
        ["home.readout.max"] = ("largest deviation", "наибольшее отклонение"),
        ["home.readout.spread"] = ("spread, 400–700 nm", "разброс, 400–700 нм"),
        ["home.readout.screen"] = ("spectrum on a screen 1 m away", "спектр на экране в 1 м"),
        ["home.readout.exit"] = ("rays that leave the glass", "лучей вышло из стекла"),
        ["home.bench.note"] = ("Each wavelength is traced through the element with the packages' own refraction; at every face the exact Fresnel split sends part out and keeps part inside, so rays fade with the energy they carry and ghosts appear where real prisms have them. Absorption over the path uses the glass's k table at the bench's millimetre scale, the temperature shifts the index through the glass's own dn/dT, and the surrounding medium has its index. Hover a ray for its wavelength, index, deviation and energy; the marks on the right are where rays land on a screen.",
            "Каждая длина волны проходит через элемент с преломлением из самих пакетов; на каждой грани точное деление Френеля часть выпускает, часть оставляет внутри — лучи тускнеют вместе с энергией, а блики появляются там же, где у настоящих призм. Поглощение на пути берётся из таблицы k стекла в миллиметровом масштабе стенда, температура сдвигает показатель через dn/dT самого стекла, у окружающей среды свой показатель. Наведи на луч — увидишь длину волны, показатель, отклонение и энергию; метки справа — где лучи легли на экран."),
        ["home.what.h"] = ("What this is", "Что это"),
        ["home.what.p1"] = ("I wanted a glass library that does not make me go back to the manufacturer's PDF for every coefficient, so I imported every manufacturer glass with a closed-form dispersion fit from the RefractiveIndex.INFO database: {0} glasses from {1} makers, {2} of them with absorption tables and {3} with temperature coefficients. Each one carries the catalog it was transcribed from, the file it came from and the date I read it.",
            "Мне нужна была библиотека стёкол, которая не гоняет за каждым коэффициентом в PDF производителя, поэтому я импортировал из базы RefractiveIndex.INFO все стёкла с аналитической формулой дисперсии: {0} стёкол от {1} производителей, у {2} из них есть таблицы поглощения, у {3} — температурные коэффициенты. У каждого записано, из какого каталога оно переписано, из какого файла взято и когда я его прочитал."),
        ["home.what.p2"] = ("I did not trust the import until I could check it, so every glass is evaluated at the exact d, F and C lines and compared with the n<sub>d</sub> and ν<sub>d</sub> its maker prints — numbers that do not depend on the fit — on every commit. N-BK7 I pinned further, to its SCHOTT datasheet for internal transmittance and dn/dT. Nothing on this site is typed in: the pages run the packages and show what comes out.",
            "Я не верил импорту, пока не смог его проверить: каждое стекло считается на точных линиях d, F и C и сверяется с n<sub>d</sub> и ν<sub>d</sub>, которые печатает производитель, — эти числа не зависят от аппроксимации, — на каждом коммите. N-BK7 прибит ещё крепче: к датащиту SCHOTT по внутреннему пропусканию и dn/dT. На сайте ничего не вписано руками: страницы запускают пакеты и показывают, что получилось."),
        ["home.map.h"] = ("Where things are", "Что где"),
        ["home.map.catalog"] = ("All {0} glasses on the Abbe diagram and in a filterable table; each opens to its curves, absorption, colour, temperature, coefficients and provenance.", "Все {0} стёкол на диаграмме Аббе и в таблице с фильтрами; у каждого — кривые, поглощение, цвет, температура, коэффициенты и происхождение."),
        ["home.map.playground"] = ("One flat interface and one slab: angle, thickness, reflectance, refraction, dispersion and the transmitted colour, all live.", "Одна плоская граница и одна пластина: угол, толщина, отражение, преломление, дисперсия и цвет на просвет — всё вживую."),
        ["home.map.render"] = ("A solid of any glass ray-traced spectrally in the browser, with the light where you put it.", "Тело из любого стекла, спектрально трассированное в браузере, со светом там, где ты его поставишь."),
        ["home.map.use"] = ("Three ways to take a glass into your own work: CSS for interfaces, GLSL for shaders, C# for computation, with the numbers filled in.", "Три способа забрать стекло к себе: CSS для интерфейсов, GLSL для шейдеров, C# для расчётов — с уже подставленными числами."),
        ["home.map.formulas"] = ("Every equation the packages evaluate, its conventions, and the type that implements it.", "Каждое уравнение, которое считают пакеты, его соглашения и тип, который его реализует."),
        ["home.map.about"] = ("Where the data comes from, how it is checked, what is not modelled, how to cite.", "Откуда данные, как они проверены, что не моделируется, как ссылаться."),
        ["home.install.h"] = ("Install", "Установка"),
        ["home.install.p"] = ("Both packages target .NET 8 and .NET 10 and depend on nothing outside the base class library.", "Оба пакета собраны под .NET 8 и .NET 10 и не зависят ни от чего вне базовой библиотеки классов."),
        ["home.use.h"] = ("Use", "Использование"),
        ["home.use.p"] = ("The numbers in the comments are computed by this page from the packages.", "Числа в комментариях эта страница вычислила пакетами."),


        // Bench (home)
        ["home.shape.biconvex"] = ("biconvex lens", "двояковыпуклая линза"),
        ["home.shape.planoconvex"] = ("plano-convex lens", "плоско-выпуклая линза"),
        ["home.shape.biconcave"] = ("biconcave lens", "двояковогнутая линза"),
        ["home.shape.meniscus"] = ("meniscus", "мениск"),
        ["home.shape.rightangle"] = ("right-angle prism", "прямоугольная призма"),
        ["home.shape.custom"] = ("your own shape", "своя фигура"),
        ["home.lens.left"] = ("Left curvature 1/R", "Кривизна слева 1/R"),
        ["home.lens.right"] = ("Right curvature 1/R", "Кривизна справа 1/R"),
        ["home.lens.thickness"] = ("Thickness", "Толщина"),
        ["home.polygon.rotation"] = ("Rotation", "Поворот"),
        ["home.plate.tilt"] = ("Tilt", "Наклон"),
        ["home.size"] = ("Size", "Размер"),
        ["home.height"] = ("Height", "Высота"),
        ["home.rays"] = ("Rays", "Лучей"),
        ["home.reflections"] = ("Fresnel reflections and ghosts", "отражения Френеля и блики"),
        ["home.medium"] = ("Surrounding medium", "Окружающая среда"),
        ["home.temperature"] = ("Glass temperature", "Температура стекла"),
        ["home.thermal.none"] = ("no dn/dT data", "нет данных dn/dT"),
        ["home.scale"] = ("Bench unit", "Единица стенда"),
        ["home.zoom"] = ("Zoom", "Масштаб"),
        ["home.bench.crossing"] = ("The outline crosses itself, so the trace has no inside and outside to work with. Move the corner back, or reset the shape.", "Контур пересекает сам себя — у трассировки нет «внутри» и «снаружи». Верни угол на место или сбрось форму."),
        ["home.bench.hint"] = ("Ctrl + wheel zooms where the cursor is, dragging the dark area moves the view, a double click puts it back.", "Ctrl + колесо приближает там, где курсор, перетаскивание тёмного поля сдвигает вид, двойной клик возвращает."),
        ["home.bench.draw"] = ("Draw your own", "Нарисовать свою"),
        ["home.bench.done"] = ("Done", "Готово"),
        ["home.bench.drawing"] = ("Click on the field to put corners down, in order around the outline. A double click or Done closes the shape; then the corners can be dragged.", "Кликай по полю, ставя углы по порядку вдоль контура. Двойной клик или «Готово» замыкает фигуру; потом углы можно таскать."),
        ["home.readout.index"] = ("n_d at this temperature", "n_d при этой температуре"),
        ["home.readout.shift"] = ("shift from the 20 °C value", "сдвиг от значения при 20 °C"),
        ["ui.more"] = ("More settings", "Ещё настройки"),
        ["home.meta"] = ("An optical bench in the browser: white light through any lens, prism or drawn shape with the refraction, Fresnel split and absorption of 1646 real glasses.", "Оптический стенд в браузере: белый свет через любую линзу, призму или нарисованную фигуру с преломлением, делением Френеля и поглощением 1646 настоящих стёкол."),
        ["render.meta"] = ("A solid of any catalog glass on a patterned table, traced on the GPU at nine wavelengths with exact Fresnel reflection, internal bounces and absorption.", "Тело из любого стекла каталога на узорчатом столе, трассировка на GPU на девяти длинах волн с точным отражением Френеля, внутренними отскоками и поглощением."),
        ["catalog.meta"] = ("1646 optical glasses from nine manufacturers with dispersion curves, absorption, thermal data, colour and provenance for every number.", "1646 оптических стёкол девяти производителей с кривыми дисперсии, поглощением, температурными данными, цветом и источником каждого числа."),
        ["home.readout.energy"] = ("energy that leaves", "энергии вышло"),
        ["home.readout.reflected"] = ("reflected at entry", "отражено на входе"),
        ["home.readout.absorbed"] = ("absorbed inside", "поглощено внутри"),
        // Catalog
        ["catalog.title"] = ("Catalog — Caustikon", "Каталог — Caustikon"),
        ["catalog.h1"] = ("Glass catalog", "Каталог стёкол"),
        ["catalog.lede"] = ("{0} glasses from {1} manufacturers. n<sub>d</sub> and ν<sub>d</sub> are the printed catalog values; every one is reproduced by its fit within five units in the fifth decimal.",
            "{0} стёкол от {1} производителей. n<sub>d</sub> и ν<sub>d</sub> — печатные каталожные значения; каждое воспроизводится аппроксимацией с точностью до пяти единиц в пятом знаке."),
        ["catalog.search"] = ("Search", "Поиск"),
        ["catalog.search.hint"] = ("N-BK7, S-LAH, 517642…", "N-BK7, S-LAH, 517642…"),
        ["catalog.vendor"] = ("Manufacturer", "Производитель"),
        ["catalog.all"] = ("All", "Все"),
        ["catalog.status"] = ("Status", "Статус"),
        ["catalog.any"] = ("Any", "Любой"),
        ["catalog.status.preferred"] = ("Preferred", "Основное"),
        ["catalog.status.standard"] = ("Standard", "Стандартное"),
        ["catalog.status.special"] = ("Special", "По запросу"),
        ["catalog.status.obsolete"] = ("Obsolete", "Снято"),
        ["catalog.status.none"] = ("Not stated", "Не указан"),
        ["catalog.from"] = ("from", "от"),
        ["catalog.to"] = ("to", "до"),
        ["catalog.shown"] = ("shown", "показано"),
        ["catalog.col.glass"] = ("Glass", "Стекло"),
        ["catalog.col.density"] = ("ρ, kg/m³", "ρ, кг/м³"),
        ["catalog.col.code"] = ("Code", "Код"),
        ["catalog.col.model"] = ("Model", "Модель"),
        ["catalog.col.range"] = ("Range, nm", "Диапазон, нм"),
        ["catalog.col.data"] = ("Data", "Данные"),
        ["abbe.hint"] = ("click a point to open the glass; hover for its name", "клик по точке открывает стекло; наведение показывает имя"),
        ["abbe.x"] = ("Abbe number ν", "Число Аббе ν"),

        // Glass page
        ["glass.notfound.h"] = ("No such glass", "Такого стекла нет"),
        ["glass.notfound.p"] = ("Nothing in the catalog is called {0} from {1}. <a href=\"catalog\">Back to the catalog</a>.", "В каталоге нет стекла {0} от {1}. <a href=\"catalog\">Назад в каталог</a>."),
        ["glass.fit"] = ("{0} fit over {1}–{2} nm", "аппроксимация {0} на {1}–{2} нм"),
        ["glass.code"] = ("code", "код"),
        ["glass.nd"] = ("n<sub>d</sub> printed, fit {0}", "n<sub>d</sub> печатный, расчёт {0}"),
        ["glass.vd"] = ("ν<sub>d</sub> printed, fit {0}", "ν<sub>d</sub> печатный, расчёт {0}"),
        ["glass.nf"] = ("n<sub>F</sub> 486.13 nm", "n<sub>F</sub> 486,13 нм"),
        ["glass.nc"] = ("n<sub>C</sub> 656.27 nm", "n<sub>C</sub> 656,27 нм"),
        ["glass.density"] = ("density, kg/m³", "плотность, кг/м³"),
        ["glass.temperature"] = ("reference temperature, K", "опорная температура, K"),
        ["glass.index.h"] = ("Refractive index", "Показатель преломления"),
        ["glass.index.note"] = ("Shaded: the visible range. Dashed: the F, d and C lines. Outside the fit interval the model reports <code>OutsideModelRange</code> instead of extrapolating.",
            "Заливка — видимый диапазон. Пунктир — линии F, d и C. Вне интервала аппроксимации модель возвращает <code>OutsideModelRange</code>, а не экстраполирует."),
        ["glass.use.h"] = ("Take this glass to:", "Взять это стекло:"),
        ["glass.derived.h"] = ("Derived numbers", "Производные числа"),
        ["glass.derived.p"] = ("Computed from the curve and the tables above at render time; nothing here is typed in. The comparison is against SCHOTT N-BK7, the crown everything is measured against.", "Считаются из кривой и таблиц выше при показе страницы; ничего здесь не вписано руками. Сравнение — с SCHOTT N-BK7, кроном, с которым сравнивают всё."),
        ["glass.derived.atd"] = ("at the d line", "на линии d"),
        ["glass.derived.group"] = ("group index at d", "групповой показатель на d"),
        ["glass.derived.vsbk7"] = ("Against N-BK7", "Относительно N-BK7"),
        ["glass.derived.r0"] = ("head-on", "при прямом взгляде"),
        ["glass.derived.r60"] = ("at 60°", "под 60°"),
        ["glass.derived.brewster"] = ("Brewster angle", "Угол Брюстера"),
        ["glass.derived.critical"] = ("Critical angle", "Критический угол"),
        ["glass.derived.rgb"] = ("at 610, 550, 465 nm", "на 610, 550, 465 нм"),
        ["glass.strips.p"] = ("Daylight after each thickness, with the share of light that gets through. The same integration as the colour panel below.", "Дневной свет после каждой толщины и доля прошедшего света. Тот же интеграл, что в цветовой панели ниже."),
        ["glass.fresnel.h"] = ("Reflectance against angle", "Отражение от угла"),
        ["glass.fresnel.p"] = ("Exact Fresnel equations for s and p polarization and their average. Entering from air, R<sub>p</sub> falls to zero at the Brewster angle, {0}°. Leaving the glass, everything reflects past the critical angle, {1}°.", "Точные уравнения Френеля для s- и p-поляризации и их среднее. При входе из воздуха R<sub>p</sub> падает до нуля под углом Брюстера, {0}°. При выходе из стекла за критическим углом, {1}°, отражается всё."),
        ["glass.fresnel.in"] = ("air → glass", "воздух → стекло"),
        ["glass.fresnel.out"] = ("glass → air", "стекло → воздух"),
        ["glass.line"] = ("Line", "Линия"),
        ["glass.absorption.h"] = ("Absorption and transmitted colour", "Поглощение и цвет на просвет"),
        ["glass.path"] = ("Path length in the glass", "Путь в стекле"),
        ["glass.surfaces"] = ("include the two air–glass surfaces at normal incidence", "учесть две границы воздух–стекло при нормальном падении"),
        ["glass.colour.srgb"] = ("sRGB", "sRGB"),
        ["glass.colour.y"] = ("Luminous transmittance Y", "Световое пропускание Y"),
        ["glass.colour.illuminant"] = ("Illuminant", "Источник"),
        ["glass.colour.illuminant.v"] = ("D65, CIE 1931 2° observer", "D65, наблюдатель CIE 1931 2°"),
        ["glass.colour.coverage"] = ("Data coverage", "Покрытие данными"),
        ["glass.colour.of"] = ("of 360–830", "из 360–830"),
        ["glass.colour.gamut"] = ("Gamut", "Охват"),
        ["glass.colour.gamut.v"] = ("outside sRGB, channels clamped", "вне sRGB, каналы обрезаны"),
        ["glass.colour.note"] = ("What a {0} mm slab does to daylight, seen against white. Bulk absorption from the manufacturer's k(λ) table{1}. Tabulated k covers {2}–{3} nm at {4} points.",
            "Что пластина {0} мм делает с дневным светом на белом фоне. Объёмное поглощение — из таблицы k(λ) производителя{1}. Таблица k покрывает {2}–{3} нм, {4} точек."),
        ["glass.colour.note.surfaces"] = (", plus Fresnel loss at both faces", ", плюс потери Френеля на обеих гранях"),
        ["glass.thermal.h"] = ("Temperature", "Температура"),
        ["glass.thermal.t"] = ("Temperature", "Температура"),
        ["glass.thermal.n"] = ("n at {0} °C", "n при {0} °C"),
        ["glass.thermal.dn"] = ("Δn<sub>abs</sub> at {0} °C", "Δn<sub>abs</sub> при {0} °C"),
        ["glass.thermal.slope"] = ("dn<sub>abs</sub>/dT at {0} °C, 10⁻⁶/K", "dn<sub>abs</sub>/dT при {0} °C, 10⁻⁶/K"),
        ["glass.thermal.note"] = ("Absolute index (against vacuum) from the manufacturer's D₀, D₁, D₂, E₀, E₁, λ<sub>TK</sub> in the SCHOTT form. The catalog index is relative to air, whose own index also moves with temperature; that conversion is not applied here.",
            "Абсолютный показатель (относительно вакуума) по коэффициентам производителя D₀, D₁, D₂, E₀, E₁, λ<sub>TK</sub> в форме SCHOTT. Каталожный показатель дан относительно воздуха, чей показатель тоже зависит от температуры; этот пересчёт здесь не применяется."),
        ["glass.model.h"] = ("Model", "Модель"),
        ["glass.model.term"] = ("term", "член"),
        ["glass.model.offset"] = ("offset", "смещение"),
        ["glass.model.power"] = ("power of λ", "степень λ"),
        ["glass.model.note"] = ("λ in micrometers. Typed constant: <code>{0}</code>.", "λ в микрометрах. Типизированная константа: <code>{0}</code>."),
        ["glass.provenance.h"] = ("Provenance", "Происхождение"),
        ["glass.provenance.source"] = ("Source", "Источник"),
        ["glass.provenance.citation"] = ("Citation", "Ссылка"),
        ["glass.provenance.reference"] = ("Reference", "Документ"),
        ["glass.provenance.path"] = ("Database path", "Путь в базе"),
        ["glass.provenance.retrieved"] = ("Retrieved", "Получено"),
        ["glass.provenance.notes"] = ("Import notes", "Заметки импорта"),
        ["glass.outside"] = ("outside fit", "вне аппроксимации"),
        ["chart.wavelength"] = ("wavelength, nm", "длина волны, нм"),

        // Playground
        ["play.title"] = ("Slab and interface calculator — Caustikon", "Калькулятор пластины и границы — Caustikon"),
        ["play.h1"] = ("Slab and interface calculator", "Калькулятор пластины и границы"),
        ["play.lede"] = ("A plane interface and a slab. Everything below is computed in your browser by the same code the packages ship.", "Плоская граница и пластина. Всё ниже считается в браузере тем же кодом, который лежит в пакетах."),
        ["play.find"] = ("Find a glass", "Найти стекло"),
        ["play.find.hint"] = ("type to narrow the list", "начни печатать, чтобы сузить список"),
        ["play.glass"] = ("Glass", "Стекло"),
        ["play.direction"] = ("Direction", "Направление"),
        ["play.airglass"] = ("air → glass", "воздух → стекло"),
        ["play.glassair"] = ("glass → air", "стекло → воздух"),
        ["play.angle"] = ("Angle of incidence", "Угол падения"),
        ["play.thickness"] = ("Slab thickness", "Толщина пластины"),
        ["play.at"] = ("at {0}° {1}", "под {0}° {1}"),
        ["play.fromInside"] = ("from inside the glass", "изнутри стекла"),
        ["play.fromAir"] = ("from air", "из воздуха"),
        ["play.col.refracted"] = ("Refracted angle", "Угол преломления"),
        ["play.critical"] = ("90° (critical)", "90° (критический)"),
        ["play.tir"] = ("total internal reflection", "полное внутреннее отражение"),
        ["play.invalid"] = ("invalid", "недопустимо"),
        ["play.note"] = ("Refraction from <code>Dielectric.RefractUnit</code>; power reflectance from <code>Dielectric.Fresnel</code>; the index of air is taken as 1 because catalog indices are already relative to air. Angular dispersion across the visible lines at this angle: {0}°.",
            "Преломление — <code>Dielectric.RefractUnit</code>; энергетическое отражение — <code>Dielectric.Fresnel</code>; показатель воздуха взят за 1, потому что каталожные показатели уже даны относительно воздуха. Угловая дисперсия по видимым линиям при этом угле: {0}°."),
        ["play.chart.r"] = ("Reflectance against angle of incidence at the d line", "Отражение в зависимости от угла падения на линии d"),
        ["play.chart.r.x"] = ("angle of incidence, °", "угол падения, °"),
        ["play.chart.r.y"] = ("reflectance", "отражение"),
        ["play.chart.a"] = ("Refracted angle against angle of incidence at the F, d and C lines", "Угол преломления в зависимости от угла падения на линиях F, d и C"),
        ["play.chart.a.y"] = ("refracted angle, °", "угол преломления, °"),
        ["play.unpolarized"] = ("unpolarized", "неполяризованный"),
        ["play.critical.note"] = ("Critical angle at the d line: {0}°. Beyond it the reflectance is exactly 1 and the transmitted direction is reported as total internal reflection rather than computed.",
            "Критический угол на линии d: {0}°. За ним отражение равно ровно 1, а вместо направления прошедшего луча сообщается полное внутреннее отражение."),
        ["play.slab.h"] = ("Through a {0} mm slab", "Через пластину {0} мм"),
        ["play.slab.colour"] = ("Transmitted colour", "Цвет на просвет"),
        ["play.slab.y"] = ("Luminous transmittance", "Световое пропускание"),
        ["play.slab.path"] = ("Path inside the glass", "Путь внутри стекла"),
        ["play.slab.text"] = ("D65 daylight enters the slab at {0}°, loses {1}% at the first face, travels {2} mm inside, and loses the same fraction again at the exit face. Bulk absorption comes from the manufacturer's k(λ) table, surface loss from the exact Fresnel equations at each wavelength, and the colour from integrating what is left against the CIE 1931 2° observer.",
            "Дневной свет D65 входит в пластину под {0}°, теряет {1}% на первой грани, проходит {2} мм внутри и теряет столько же на выходе. Объёмное поглощение — из таблицы k(λ) производителя, потери на гранях — по точным уравнениям Френеля для каждой длины волны, цвет — интегрированием остатка по наблюдателю CIE 1931 2°."),
        ["play.slab.coverage"] = ("The absorption table for this glass covers {0}–{1} nm; outside it the nearest tabulated value is held constant.", "Таблица поглощения этого стекла покрывает {0}–{1} нм; вне её берётся ближайшее табличное значение."),
        ["play.slab.nok"] = ("This glass has no absorption table in its catalog entry, so no transmitted colour is computed.", "У этого стекла в каталоге нет таблицы поглощения, поэтому цвет на просвет не считается."),
        ["spectrum.slab"] = ("Visible spectrum through the {0} mm slab", "Видимый спектр через пластину {0} мм"),
        ["spectrum.glass"] = ("Visible spectrum through {0} mm of {1}", "Видимый спектр через {0} мм {1}"),

        // Render
        ["render.title"] = ("Render — Caustikon", "Рендер — Caustikon"),
        ["render.h1"] = ("Render", "Рендер"),
        ["render.lede"] = ("A solid of the chosen glass on a patterned ground, ray-traced in your browser with the packages' own refraction, reflectance and absorption at nine wavelengths. The fringes and the tint are computed, not drawn.",
            "Тело из выбранного стекла на узорчатом столе, трассированное в браузере преломлением, отражением и поглощением из самих пакетов на девяти длинах волн. Каймы и оттенок вычислены, а не нарисованы."),
        ["render.glass"] = ("Glass", "Стекло"),
        ["render.common"] = ("Commonly used", "Ходовые"),
        ["render.solid"] = ("Solid", "Тело"),
        ["render.solid.sphere"] = ("sphere", "шар"),
        ["render.solid.cube"] = ("cube", "куб"),
        ["render.solid.prism"] = ("prism", "призма"),
        ["render.solid.octahedron"] = ("octahedron", "октаэдр"),
        ["render.solid.dodecahedron"] = ("dodecahedron", "додекаэдр"),
        ["render.solid.icosahedron"] = ("icosahedron", "икосаэдр"),
        ["render.faces"] = ("Prism faces", "Граней призмы"),
        ["render.size"] = ("Size", "Размер"),
        ["render.backdrop"] = ("Backdrop", "Фон"),
        ["render.backdrop.checker"] = ("checker", "клетка"),
        ["render.backdrop.stripes"] = ("colour bands", "цветные полосы"),
        ["render.backdrop.grid"] = ("millimetre paper", "миллиметровка"),
        ["render.backdrop.paper"] = ("plain paper", "бумага"),
        ["render.backdrop.night"] = ("night", "ночь"),
        ["render.light.az"] = ("Light around", "Свет по кругу"),
        ["render.light.el"] = ("Light height", "Высота света"),
        ["render.lamp"] = ("Lamp", "Лампа"),
        ["render.zoom"] = ("Zoom", "Масштаб"),
        ["render.zoom.in"] = ("Closer", "Ближе"),
        ["render.zoom.out"] = ("Farther", "Дальше"),
        ["render.exposure"] = ("Exposure", "Экспозиция"),
        ["render.room"] = ("Room", "Комната"),
        ["render.resolution"] = ("Resolution", "Разрешение"),
        ["render.button"] = ("Render", "Рендерить"),
        ["render.rendering"] = ("Rendering… {0}%", "Рендер… {0}%"),
        ["render.fact.glass"] = ("Glass", "Стекло"),
        ["render.fact.n"] = ("n at 400 and 700 nm", "n на 400 и 700 нм"),
        ["render.fact.tau"] = ("τ<sub>i</sub> across {0} mm at 450 / 650 nm", "τ<sub>i</sub> через {0} мм на 450 / 650 нм"),
        ["render.fact.ground"] = ("Ground pattern", "Узор стола"),
        ["render.fact.ground.v"] = ("16 mm tiles, so the solid's size reads against them; lit by the room and by the lamp through the solid", "клетка 16 мм, размер тела читается по ней; освещена комнатой и лампой сквозь тело"),
        ["render.fact.samples"] = ("Sampled wavelengths", "Длины волн"),
        ["render.orbit"] = ("Drag to turn the solid, Ctrl + wheel to come closer, double click to go back. Every frame is traced on the graphics card.", "Тяни, чтобы повернуть тело, Ctrl + колесо — приблизиться, двойной клик — вернуть как было. Каждый кадр трассируется на видеокарте."),
        ["render.cpu"] = ("This browser has no WebGL2, so the picture is traced on the processor: pick a resolution and press Render.", "В этом браузере нет WebGL2, картинка считается на процессоре: выбери разрешение и нажми «Рендерить»."),
        ["render.fact.gpu"] = ("Where it runs", "Где считается"),
        ["render.fact.gpu.v"] = ("a WebGL2 fragment shader; nine wavelengths per sample with a random offset inside each band, up to 48 samples per pixel when still; the lamp's shadow and caustic from a photon pass; ACES tone curve", "фрагментный шейдер WebGL2; девять длин волн на сэмпл со случайным сдвигом внутри полосы, до 48 сэмплов на пиксель в покое; тень и каустика лампы из фотонного прохода; тоновая кривая ACES"),
        ["render.fact.time"] = ("Tracing time", "Время трассировки"),
        ["render.fact.time.v"] = ("{0} × {0} in {1} s; {2} edge pixels supersampled", "{0} × {0} за {1} с; {2} краевых пикселей с суперсэмплингом"),
        ["render.note"] = ("Each pixel traces nine rays, one per wavelength: Fresnel-weighted reflection off the surface, refraction in, up to six internal reflections with Beer–Lambert absorption over every chord from the glass's k(λ) table, refraction out. A flint spreads pattern edges into colour; a thick dense flint goes warm because its own k(λ) says so. Not simulated: shadows, caustics on the ground, coatings, polarization beyond the unpolarized split.",
            "Каждый пиксель — девять лучей, по одному на длину волны: отражение от поверхности с весом Френеля, преломление внутрь, до шести внутренних отражений с поглощением Бугера–Ламберта на каждой хорде по таблице k(λ) стекла, преломление наружу. Флинт разводит края узора в цвет; толстый плотный флинт теплеет, потому что так говорит его собственная k(λ). Не моделируются: тени, каустики на столе, просветление, поляризация сверх неполяризованного разбиения."),
        ["render.nok"] = ("no k data", "нет данных k"),



        // Calculator
        ["calc.h"] = ("Calculator", "Расчёт"),
        ["calc.lede"] = ("One glass, one wavelength, one angle: every quantity a design needs, from the packages, laid out like a datasheet.", "Одно стекло, одна длина волны, один угол: все величины, нужные расчёту, из пакетов, в виде датащита."),
        ["calc.glass"] = ("Glass", "Стекло"),
        ["calc.wavelength"] = ("Wavelength λ, nm", "Длина волны λ, нм"),
        ["calc.lines"] = ("Spectral lines", "Спектральные линии"),
        ["calc.angle"] = ("Angle of incidence θ, °", "Угол падения θ, °"),
        ["calc.apex"] = ("Prism apex A, °", "Преломляющий угол призмы A, °"),
        ["calc.thickness"] = ("Slab thickness d, mm", "Толщина пластины d, мм"),
        ["calc.sec.index"] = ("Index at λ", "Показатель на λ"),
        ["calc.n.note"] = ("phase index from the catalog fit", "фазовый показатель по каталожной аппроксимации"),
        ["calc.dndl.note"] = ("central difference over ±1 nm", "центральная разность на ±1 нм"),
        ["calc.ng.note"] = ("group index: what a pulse sees", "групповой показатель: то, что видит импульс"),
        ["calc.v.note"] = ("phase velocity", "фазовая скорость"),
        ["calc.lambda.note"] = ("wavelength inside the glass", "длина волны внутри стекла"),
        ["calc.sec.dispersion"] = ("Dispersion", "Дисперсия"),
        ["calc.vd.note"] = ("from the fit; printed:", "по аппроксимации; печатный:"),
        ["calc.ve.note"] = ("mercury-line Abbe number", "число Аббе по ртутной линии e"),
        ["calc.pgf.note"] = ("relative partial dispersion g–F", "относительная частная дисперсия g–F"),
        ["calc.sec.interface"] = ("Plane interface", "Плоская граница"),
        ["calc.airglass"] = ("air → glass", "воздух → стекло"),
        ["calc.glassair"] = ("glass → air", "стекло → воздух"),
        ["calc.r.note"] = ("exact Fresnel power reflectances, air → glass", "точные энергетические коэффициенты Френеля, воздух → стекло"),
        ["calc.t.note"] = ("into the glass, unpolarized", "в стекло, неполяризованный свет"),
        ["calc.brewster.note"] = ("Brewster: R_p = 0, air → glass", "угол Брюстера: R_p = 0, воздух → стекло"),
        ["calc.critical.note"] = ("critical angle inside the glass", "критический угол внутри стекла"),
        ["calc.out.note"] = ("the same θ taken from inside", "тот же θ, но изнутри стекла"),
        ["calc.rout.note"] = ("unpolarized, 1 beyond the critical angle", "неполяризованный, 1 за критическим углом"),
        ["calc.sec.slab"] = ("Slab at θ", "Пластина под θ"),
        ["calc.path"] = ("Path inside", "Путь внутри"),
        ["calc.shift"] = ("Lateral displacement", "Боковое смещение"),
        ["calc.tau.note"] = ("internal transmittance over that path, from the k table", "внутреннее пропускание на этом пути, по таблице k"),
        ["calc.tslab.note"] = ("two faces, s and p tracked separately, plus absorption", "две грани, s и p раздельно, плюс поглощение"),
        ["calc.sec.prism"] = ("Prism", "Призма"),
        ["calc.dmin.note"] = ("incidence that gives the minimum", "угол падения, дающий минимум"),
        ["calc.dev.note"] = ("deviation at the angle above, symmetric prism", "отклонение при заданном угле, симметричная призма"),
        ["calc.disp.note"] = ("angular dispersion at θ", "угловая дисперсия при θ"),
        ["calc.spreadFC.note"] = ("F to C spread at θ", "разброс F–C при θ"),
        ["calc.noPass"] = ("no transmission: n·sin(A/2) > 1", "не проходит: n·sin(A/2) > 1"),
        // Glass for UI
        ["use.title"] = ("Glass for UI — Caustikon", "Стекло для интерфейса — Caustikon"),
        ["use.meta"] = ("A real optical glass over an interface: bevel refraction, colour fringes, Fresnel sheen and tint from the catalog, with the shader and CSS to copy.", "Настоящее оптическое стекло над интерфейсом: преломление на фаске, цветные каймы, френелевский блеск и оттенок из каталога, плюс шейдер и CSS для копирования."),
        ["use.h1"] = ("Glass for an interface", "Стекло для интерфейса"),
        ["use.lede"] = ("A panel of a real glass over a page. Pick the glass and the thickness, shape the bevel, and watch the edges bend and split colour the way that glass does. The shader that draws it is yours to copy; the CSS below approximates what CSS can.", "Панель из настоящего стекла над страницей. Выбери стекло и толщину, задай фаску и смотри, как края гнут и раскладывают цвет ровно так, как это стекло. Шейдер, который это рисует, можно забрать целиком; CSS ниже приближает то, что CSS вообще умеет."),
        ["use.hint"] = ("Every pixel is traced: the view refracts into the glass at the bevel and the dome, crosses the thickness, and reads the page where it lands. Red, green and blue each use their own index, so fringes appear where that glass puts them.", "Каждый пиксель трассируется: взгляд преломляется в стекло на фаске и куполе, проходит толщину и читает страницу там, куда попал. У красного, зелёного и синего свой показатель, поэтому каймы появляются там, где их даёт это стекло."),
        ["use.nogl"] = ("This browser has no WebGL2, so only the CSS approximation below can be shown.", "В этом браузере нет WebGL2, поэтому показать можно только CSS-приближение ниже."),
        ["use.glass"] = ("Glass", "Стекло"),
        ["use.thickness"] = ("Thickness", "Толщина"),
        ["use.bevel"] = ("Bevel width", "Ширина фаски"),
        ["use.dome"] = ("Dome", "Купол"),
        ["use.frost"] = ("Frost", "Матовость"),
        ["use.radius"] = ("Corner radius", "Скругление углов"),
        ["use.light"] = ("Light direction", "Направление света"),
        ["use.scale"] = ("Pixels per millimetre", "Пикселей на миллиметр"),
        ["use.width"] = ("Panel width", "Ширина панели"),
        ["use.height"] = ("Panel height", "Высота панели"),
        ["use.readout.kind"] = ("glass family", "семейство"),
        ["use.readout.face"] = ("reflected looking straight at it", "отражается при прямом взгляде"),
        ["use.readout.edge"] = ("reflected at 60°, on the bevel", "отражается под 60°, на фаске"),
        ["use.readout.fringe"] = ("colour fringe on the bevel", "цветная кайма на фаске"),
        ["use.readout.tint"] = ("daylight after {0} mm", "дневной свет после {0} мм"),
        ["use.readout.luminance"] = ("of the light gets through", "света проходит"),
        ["use.kind.crown"] = ("Crown", "Крон"),
        ["use.kind.middle"] = ("In between", "Промежуточное"),
        ["use.kind.flint"] = ("Flint", "Флинт"),
        ["use.say"] = ("{0} is a {1}: index {2}, Abbe number {3}. {4} {5}: it returns {6}% of the light head-on. {7} at {8} mm.", "{0} — {1}: показатель {2}, число Аббе {3}. {4} {5}: при прямом взгляде возвращает {6}% света. {7} на {8} мм."),
        ["use.say.fringe.none"] = ("The bevel stays almost colourless;", "Фаска почти не окрашивается;"),
        ["use.say.fringe.some"] = ("The bevel shows thin colour fringes up close;", "На фаске вблизи видны тонкие цветные каймы;"),
        ["use.say.fringe.strong"] = ("The bevel splits colour visibly, like a cut stone;", "Фаска заметно раскладывает цвет, как огранённый камень;"),
        ["use.say.sheen.low"] = ("the face has a quiet sheen", "лицо блестит сдержанно"),
        ["use.say.sheen.mid"] = ("the face has a noticeable gloss", "лицо заметно глянцевое"),
        ["use.say.sheen.high"] = ("the face is glossy like a gem", "лицо блестит как у камня"),
        ["use.say.tint.none"] = ("No tint to speak of", "Оттенка практически нет"),
        ["use.say.tint.warm.slight"] = ("A faint warm tint", "Едва тёплый оттенок"),
        ["use.say.tint.cool.slight"] = ("A faint cool tint", "Едва холодный оттенок"),
        ["use.say.tint.warm"] = ("A clear warm, yellowish tint", "Явный тёплый, желтоватый оттенок"),
        ["use.say.tint.cool"] = ("A clear cool tint", "Явный холодный оттенок"),
        ["use.backdrop.title"] = ("An interface behind the glass", "Интерфейс за стеклом"),
        ["use.what.h"] = ("What changes between glasses", "Что меняется от стекла к стеклу"),
        ["use.what.p1"] = ("Three things, and each is a number from the catalog. The index sets how hard the bevel bends the page and how much the face reflects: at 1.52 a window returns four per cent of the light, at 1.78 it returns almost eight and looks glossy. The Abbe number sets how far red and blue part on the bevel: above sixty they stay together, below thirty they split into a visible rainbow. The absorption table sets the tint that grows with thickness; a dense flint goes warm at twenty millimetres, a fluor crown stays clear at forty.", "Три вещи, и каждая — число из каталога. Показатель задаёт, как сильно фаска гнёт страницу и сколько отражает лицо: при 1,52 окно возвращает четыре процента света, при 1,78 почти восемь и выглядит глянцевым. Число Аббе задаёт, насколько на фаске расходятся красный и синий: выше шестидесяти они держатся вместе, ниже тридцати расходятся в заметную радугу. Таблица поглощения задаёт оттенок, который растёт с толщиной: плотный флинт теплеет на двадцати миллиметрах, фторкрон остаётся прозрачным на сорока."),
        ["use.what.p2"] = ("Frost is not a glass property. Real frosted glass is a rough surface that scatters light; here it is a blur radius, kept separate so the physics stays honest and the design stays yours.", "Матовость — не свойство стекла. Настоящее матовое стекло — шероховатая поверхность, которая рассеивает свет; здесь это радиус размытия, вынесенный отдельно, чтобы физика оставалась честной, а дизайн — твоим."),
        ["use.shape"] = ("Shape", "Форма"),
        ["use.shape.rect"] = ("rounded rectangle", "скруглённый прямоугольник"),
        ["use.shape.pill"] = ("pill", "пилюля"),
        ["use.shape.circle"] = ("circle", "круг"),
        ["use.backdrop"] = ("Behind the glass", "За стеклом"),
        ["use.backdrop.interface"] = ("an interface", "интерфейс"),
        ["use.backdrop.text"] = ("dense text", "плотный текст"),
        ["use.backdrop.photo"] = ("a photograph", "фотография"),
        ["use.backdrop.dark"] = ("a dark interface", "тёмный интерфейс"),
        ["use.lightstrength"] = ("Lamp", "Лампа"),
        ["use.compare"] = ("Compare with", "Сравнить с"),
        ["use.compare.none"] = ("nothing", "ни с чем"),
        ["use.compare.hint"] = ("The same panel in {0}, for comparison.", "Та же панель из {0}, для сравнения."),
        ["use.download"] = ("Save as PNG", "Сохранить PNG"),
        ["use.code.h"] = ("Take it with you", "Забрать с собой"),
        ["use.more.formats"] = ("More formats for this glass: Tailwind, Figma and the Give Me! pages.", "Другие форматы для этого стекла: Tailwind, Figma и страницы Give Me!."),
        ["use.glsl.h"] = ("The shader, as drawn above", "Шейдер, как на картинке"),
        ["use.glsl.p"] = ("GLSL ES 3.00 with this glass's indices and absorption baked in. Feed it a texture of what sits behind the panel and the panel size; it draws the bevel, the dome, the fringes, the sheen and the tint. Nothing in it is tuned by eye.", "GLSL ES 3.00 с зашитыми показателями и поглощением этого стекла. Дай ему текстуру того, что лежит за панелью, и размер панели; он нарисует фаску, купол, каймы, блеск и оттенок. Ничего в нём не подобрано на глаз."),
        ["use.css.h"] = ("The CSS approximation", "CSS-приближение"),
        ["use.css.p"] = ("CSS cannot refract, so the bend and the fringes are missing here. What it can carry is the tint, how much light gets through, and the Fresnel numbers as highlight strengths, so a card still reads as this particular glass rather than a generic blur.", "CSS не умеет преломлять, поэтому излома и кайм здесь нет. Что он может нести — оттенок, долю прошедшего света и числа Френеля как силу бликов, чтобы карточка читалась именно как это стекло, а не как размытие вообще."),
        ["use.demo.text"] = ("Text behind the glass keeps its colour where the glass is clear and loses blue where the glass is a dense flint.", "Текст за стеклом сохраняет цвет там, где стекло прозрачно, и теряет синий там, где стекло — плотный флинт."),
        ["use.copy"] = ("Copy", "Копировать"),
        ["use.cs.h"] = ("The same numbers in .NET", "Те же числа в .NET"),
        ["use.cs.p"] = ("For a renderer or a tool that computes rather than draws: the typed constant is a value type for the ray path, the catalog entry carries the absorption and the provenance.", "Для рендерера или инструмента, который считает, а не рисует: типизированная константа — значимый тип для трассировки, запись каталога несёт поглощение и источник."),
        ["use.pick.h"] = ("Which glass to take", "Какое стекло взять"),
        ["use.pick.p"] = ("Four that cover most interface work. Each line ends with its index, Abbe number and how much light the face returns.", "Четыре, которых хватает на большинство интерфейсных задач. В конце каждой строки — показатель, число Аббе и сколько света возвращает лицо."),
        ["use.pick.numbers"] = ("n_d {0}, ν_d {1}, face {2}%.", "n_d {0}, ν_d {1}, лицо {2}%."),

        // Formulas
        ["formulas.title"] = ("Formulas — Caustikon", "Формулы — Caustikon"),
        ["formulas.h1"] = ("Formulas", "Формулы"),
        ["formulas.lede"] = ("Every equation the packages evaluate, with the conventions that make its numbers comparable to a catalog, and the type that implements it.", "Каждое уравнение, которое считают пакеты, с соглашениями, делающими его числа сравнимыми с каталогом, и типом, который его реализует."),
        ["formulas.refraction.h"] = ("Refraction", "Преломление"),
        ["formulas.refraction.p"] = ("<code>Dielectric.RefractUnit</code> takes unit vectors rather than angles. With η = n<sub>i</sub>/n<sub>t</sub>, the incident direction I and a normal N pointing into the incident medium, the transmitted direction is η·I<sub>tangent</sub> − √(1 − η²|I<sub>tangent</sub>|²)·N. When the square root's argument is negative the call reports total internal reflection; within eight units of single-precision epsilon of zero it reports the critical angle and returns the tangent direction. Both indices must share a reference medium: catalog indices are relative to air, so air is 1.",
            "<code>Dielectric.RefractUnit</code> принимает единичные векторы, а не углы. При η = n<sub>i</sub>/n<sub>t</sub>, направлении падения I и нормали N, направленной в падающую среду, прошедшее направление равно η·I<sub>tangent</sub> − √(1 − η²|I<sub>tangent</sub>|²)·N. Когда подкоренное выражение отрицательно, вызов сообщает полное внутреннее отражение; в пределах восьми единиц машинного эпсилон одинарной точности от нуля — критический угол и возвращает касательное направление. Оба показателя должны быть относительно одной среды: каталожные даны относительно воздуха, поэтому воздух равен 1."),
        ["formulas.fresnel.h"] = ("Fresnel power reflectance", "Энергетические коэффициенты Френеля"),
        ["formulas.fresnel.p"] = ("<code>Dielectric.Fresnel</code> returns both polarizations; unpolarized light is their mean. Beyond the critical angle both are 1. Two surfaces in series must be composed per polarization, (T<sub>s1</sub>T<sub>s2</sub> + T<sub>p1</sub>T<sub>p2</sub>)/2, because light is partially polarized after the first; the playground does this. At normal incidence both reduce to R₀ = ((n<sub>i</sub> − n<sub>t</sub>)/(n<sub>i</sub> + n<sub>t</sub>))², <code>Dielectric.NormalReflectance</code>, and Schlick's approximation R₀ + (1 − R₀)(1 − cos θ)⁵ is <code>Dielectric.Schlick</code>; it does not know about total internal reflection.",
            "<code>Dielectric.Fresnel</code> возвращает обе поляризации; неполяризованный свет — их среднее. За критическим углом обе равны 1. Две границы подряд складываются по поляризациям, (T<sub>s1</sub>T<sub>s2</sub> + T<sub>p1</sub>T<sub>p2</sub>)/2, потому что после первой свет частично поляризован; стенд так и делает. При нормальном падении обе сводятся к R₀ = ((n<sub>i</sub> − n<sub>t</sub>)/(n<sub>i</sub> + n<sub>t</sub>))², <code>Dielectric.NormalReflectance</code>, а приближение Шлика R₀ + (1 − R₀)(1 − cos θ)⁵ — это <code>Dielectric.Schlick</code>; о полном внутреннем отражении оно не знает."),
        ["formulas.dispersion.h"] = ("Dispersion", "Дисперсия"),
        ["formulas.dispersion.p"] = ("λ is in micrometers in every form. Each model carries the wavelength interval its coefficients were fitted over and refuses to extrapolate.", "λ во всех формах в микрометрах. Каждая модель несёт интервал длин волн, на котором подобраны коэффициенты, и не экстраполирует."),
        ["formulas.sellmeier.h"] = ("Sellmeier — <code>Sellmeier</code>, <code>Sellmeier3</code>", "Зельмейер — <code>Sellmeier</code>, <code>Sellmeier3</code>"),
        ["formulas.sellmeier.p"] = ("C<sub>i</sub> is the squared resonance wavelength in µm². SCHOTT, OHARA and CDGM publish this form. A source that lists the resonance wavelengths themselves is imported by squaring them. A positive C<sub>i</sub> puts a pole at 1000·√C<sub>i</sub> nm; a model whose interval contains an active pole cannot be constructed. Negative C<sub>i</sub>, which several CDGM fits carry, has no pole and is accepted.",
            "C<sub>i</sub> — квадрат резонансной длины волны в мкм². В этой форме публикуют SCHOTT, OHARA и CDGM. Источник, где даны сами резонансные длины волн, импортируется возведением их в квадрат. Положительный C<sub>i</sub> даёт полюс на 1000·√C<sub>i</sub> нм; модель, чей интервал содержит активный полюс, не строится. Отрицательный C<sub>i</sub>, который есть у нескольких аппроксимаций CDGM, полюса не имеет и принимается."),
        ["formulas.polynomial.h"] = ("Polynomial — <code>Polynomial</code>", "Полином — <code>Polynomial</code>"),
        ["formulas.polynomial.p"] = ("The older \"SCHOTT formula\", still used by HOYA, SUMITA, HIKARI and part of OHARA, with powers 2, −2, −4, −6, −8 and sometimes −10, −12. Even integer powers are evaluated by repeated multiplication or division applied to the coefficient, so a small coefficient over a short wavelength cannot overflow before the ratio is formed.",
            "Старая «формула SCHOTT», которой до сих пор пользуются HOYA, SUMITA, HIKARI и часть OHARA, со степенями 2, −2, −4, −6, −8, иногда −10, −12. Чётные целые степени считаются повторным умножением или делением коэффициента, поэтому малый коэффициент на короткой длине волны не переполнится раньше, чем сложится отношение."),
        ["formulas.cauchy.h"] = ("Cauchy — <code>Cauchy</code>, <code>Cauchy3</code>", "Коши — <code>Cauchy</code>, <code>Cauchy3</code>"),
        ["formulas.cauchy.p"] = ("The same series in n rather than n²; index-matching liquids are catalogued this way.", "Тот же ряд по n, а не по n²; так каталогизированы иммерсионные жидкости."),
        ["formulas.abbe.h"] = ("Abbe number", "Число Аббе"),
        ["formulas.abbe.p"] = ("d = 587.5618 nm (He), F = 486.1327 nm (H), C = 656.2725 nm (H): <code>FraunhoferLines</code>. ν<sub>d</sub> divides by a difference of two nearly equal numbers, which is why the catalog tests use it: an error in the fourth decimal of a coefficient shows up there and nowhere else.",
            "d = 587,5618 нм (He), F = 486,1327 нм (H), C = 656,2725 нм (H): <code>FraunhoferLines</code>. ν<sub>d</sub> делит на разность двух почти равных чисел, поэтому тесты каталога используют именно его: ошибка в четвёртом знаке коэффициента видна там и больше нигде."),
        ["formulas.absorption.h"] = ("Absorption", "Поглощение"),
        ["formulas.absorption.p"] = ("<code>TabulatedExtinction</code> holds the manufacturer's k(λ) and interpolates it linearly in log k, because k spans several orders of magnitude across the visible. τ<sub>i</sub> is internal transmittance: bulk only, no surface reflection. Manufacturers print τ<sub>i</sub> for 10 mm and 25 mm; the catalog reproduces SCHOTT's N-BK7 columns within their printed precision.",
            "<code>TabulatedExtinction</code> хранит k(λ) производителя и интерполирует линейно по log k, потому что k меняется на несколько порядков по видимому диапазону. τ<sub>i</sub> — внутреннее пропускание: только объём, без отражения на гранях. Производители печатают τ<sub>i</sub> для 10 и 25 мм; каталог воспроизводит столбцы SCHOTT для N-BK7 в пределах печатной точности."),
        ["formulas.thermal.h"] = ("Temperature", "Температура"),
        ["formulas.thermal.p"] = ("<code>ThermalDispersion</code>, the form from SCHOTT TIE-19, with ΔT from 20 °C. It gives the change of the absolute index. The relative index also depends on how air's index moves with temperature, which is not modelled. For N-BK7 the result matches the datasheet's Δn<sub>abs</sub>/ΔT in all nine printed cells.",
            "<code>ThermalDispersion</code> — форма из SCHOTT TIE-19, ΔT от 20 °C. Даёт изменение абсолютного показателя. Относительный зависит ещё и от того, как с температурой меняется показатель воздуха, — это не моделируется. Для N-BK7 результат совпадает с Δn<sub>abs</sub>/ΔT датащита во всех девяти напечатанных ячейках."),
        ["formulas.colour.h"] = ("Colour", "Цвет"),
        ["formulas.colour.p"] = ("<code>GlassColour</code> integrates over 360–830 nm at 1 nm with the CIE 1931 2° observer and illuminant D65, normalized so that a perfect transmitter has Y = 1. Y is therefore the luminous transmittance. Channels are clamped to [0, 1] and the result says whether clamping happened.",
            "<code>GlassColour</code> интегрирует по 360–830 нм с шагом 1 нм по наблюдателю CIE 1931 2° и источнику D65, с нормировкой, при которой идеальный пропускатель даёт Y = 1. Y, таким образом, — световое пропускание. Каналы обрезаются до [0, 1], и результат сообщает, было ли обрезание."),
        ["formulas.colour.eq2"] = ("then the sRGB transfer curve", "затем передаточная кривая sRGB"),
        ["formulas.colour.eq1"] = ("likewise Y, Z", "аналогично Y, Z"),

        // About
        ["about.meta"] = ("What Caustikon is, where its 1646 glasses come from, how each number is checked, how to install the packages and what is out of scope.", "Что такое Caustikon, откуда его 1646 стёкол, как проверяется каждое число, как поставить пакеты и что вне рамок."),
        ["home.map.design"] = ("A glass panel over an interface, traced in a shader; the shader, CSS and .NET to copy.", "Стеклянная панель над интерфейсом, трассировка в шейдере; шейдер, CSS и .NET для копирования."),
        ["home.map.bench"] = ("The optical bench: any lens, prism or drawn shape, white light through it, the full refraction calculator beneath.", "Оптический стенд: любая линза, призма или нарисованная фигура, белый свет сквозь неё, полный калькулятор преломления под ним."),
        ["home.map.give"] = ("One page per craft: design, games, 3D and Blender, web, .NET. Pick a glass, get the numbers in every format with each value explained.", "По странице на ремесло: дизайн, игры, 3D и Blender, веб, .NET. Выбери стекло, получи числа в каждом формате с пояснением каждого значения."),
        ["about.author.h"] = ("Author", "Автор"),
        ["about.author.p"] = ("Made by <a href=\"https://github.com/levvs-one\" rel=\"noopener\">levvs-one</a>. Source, issues and releases live in the <a href=\"https://github.com/levvs-one/caustikon\" rel=\"noopener\">repository</a>.", "Автор — <a href=\"https://github.com/levvs-one\" rel=\"noopener\">levvs-one</a>. Исходники, задачи и релизы — в <a href=\"https://github.com/levvs-one/caustikon\" rel=\"noopener\">репозитории</a>."),
        ["about.title"] = ("About — Caustikon", "О проекте — Caustikon"),
        ["about.h1"] = ("About", "О проекте"),
        ["about.lede"] = ("Caustikon is two .NET packages and this site. The packages are the product; the site runs them in your browser so the numbers can be inspected without installing anything.", "Caustikon — это два пакета .NET и этот сайт. Продукт — пакеты; сайт запускает их в браузере, чтобы числа можно было разглядеть, ничего не устанавливая."),
        ["about.data.h"] = ("Where the data comes from", "Откуда данные"),
        ["about.data.p1"] = ("Every catalogued glass is transcribed from the RefractiveIndex.INFO database, which Mikhail Polyanskiy released into the public domain under CC0 1.0. The database in turn transcribes manufacturer catalogs; each entry here names that catalog release, links to the entry's file in the database, and records the date the database was read. The current import is commit {0}, read on {1}.",
            "Каждое стекло каталога переписано из базы RefractiveIndex.INFO, которую Михаил Полянский передал в общественное достояние под CC0 1.0. База в свою очередь переписывает каталоги производителей; каждая запись здесь называет выпуск каталога, ссылается на файл записи в базе и хранит дату чтения базы. Текущий импорт — коммит {0}, прочитан {1}."),
        ["about.data.p2"] = ("Of {0} manufacturer entries in the database, {1} have closed-form dispersion and are included. The rest are tabulated-only (filters, some infrared and matching materials) and are listed by path and reason in the repository's <a href=\"https://github.com/levvs-one/caustikon/blob/main/data/glasses/manifest.json\" rel=\"noopener\">manifest</a>.",
            "Из {0} записей производителей в базе {1} имеют аналитическую дисперсию и включены. Остальные заданы только таблицами (фильтры, часть ИК-материалов и иммерсионных сред) и перечислены с путём и причиной в <a href=\"https://github.com/levvs-one/caustikon/blob/main/data/glasses/manifest.json\" rel=\"noopener\">манифесте</a> репозитория."),
        ["about.data.p3"] = ("Colour uses the CIE 1931 2° observer at 1 nm and illuminant D65 at 5 nm, copied unchanged from the colour-science project's data tables (BSD-3-Clause). Licences and citations: <a href=\"https://github.com/levvs-one/caustikon/blob/main/DATA-LICENSE.md\" rel=\"noopener\">DATA-LICENSE.md</a>.",
            "Цвет считается по наблюдателю CIE 1931 2° с шагом 1 нм и источнику D65 с шагом 5 нм, скопированным без изменений из таблиц проекта colour-science (BSD-3-Clause). Лицензии и ссылки: <a href=\"https://github.com/levvs-one/caustikon/blob/main/DATA-LICENSE.md\" rel=\"noopener\">DATA-LICENSE.md</a>."),
        ["about.check.h"] = ("How the numbers are checked", "Как проверяются числа"),
        ["about.check.p1"] = ("A dispersion fit and the printed n<sub>d</sub> of a glass are two independent statements by the manufacturer. On every commit, the test suite evaluates all {0} models at the exact d, F and C lines and compares with the printed n<sub>d</sub> and ν<sub>d</sub>. The bound on n<sub>d</sub> is five units in the fifth decimal plus the rounding of the printed value; the bound on ν<sub>d</sub> is that bound propagated through its definition. All pass. The largest deviation in the catalog, and which glass it belongs to, is recorded in the manifest.",
            "Аппроксимация дисперсии и напечатанный n<sub>d</sub> — два независимых утверждения производителя. На каждом коммите тесты считают все {0} моделей на точных линиях d, F и C и сравнивают с напечатанными n<sub>d</sub> и ν<sub>d</sub>. Допуск по n<sub>d</sub> — пять единиц в пятом знаке плюс округление напечатанного значения; допуск по ν<sub>d</sub> — тот же, протянутый через его определение. Проходят все. Наибольшее отклонение в каталоге и стекло, которому оно принадлежит, записаны в манифесте."),
        ["about.check.p2"] = ("N-BK7 is pinned further, to the SCHOTT datasheet of 1 December 2023: seven internal-transmittance rows at 10 mm and 25 mm and nine dn/dT cells across three temperature ranges and three lines, each within the datasheet's printed precision. D65 through a perfect transmitter reproduces the D65 white point.",
            "N-BK7 прибит крепче — к датащиту SCHOTT от 1 декабря 2023: семь строк внутреннего пропускания при 10 и 25 мм и девять ячеек dn/dT по трём диапазонам температур и трём линиям, каждая в пределах печатной точности датащита. D65 через идеальный пропускатель воспроизводит белую точку D65."),
        ["about.limits.h"] = ("What is not modelled", "Что не моделируется"),
        ["about.limits.p"] = ("Absorption is bulk only, from tabulated k; there is no scattering, no coating, no surface roughness. The index of air is 1 and does not change with temperature or pressure, so temperature results are absolute-index shifts. There is no birefringence, no polarization state beyond s and p power fractions at an interface, no thin-film interference, no diffraction. The packages compute what happens at a plane dielectric boundary and in a homogeneous slab; scene geometry, lenses and rendering belong to the caller.",
            "Поглощение — только объёмное, по таблице k; нет рассеяния, просветления, шероховатости. Показатель воздуха равен 1 и не зависит от температуры и давления, поэтому температурные результаты — сдвиги абсолютного показателя. Нет двулучепреломления, нет состояния поляризации сверх долей мощности s и p на границе, нет тонкоплёночной интерференции, нет дифракции. Пакеты считают, что происходит на плоской диэлектрической границе и в однородной пластине; геометрия сцены, линзы и рендеринг — забота вызывающего."),
        ["about.packages.h"] = ("Packages", "Пакеты"),
        ["about.packages.p"] = ("<code>Caustikon</code> is the mathematics: refraction, Fresnel, the dispersion models. <code>Caustikon.Glasses</code> is the catalog with absorption, temperature and colour. Both target .NET 8 and .NET 10 with no dependencies beyond the base class library. Source, issues and the data of record are on <a href=\"https://github.com/levvs-one/caustikon\" rel=\"noopener\">GitHub</a>, under the MIT licence.",
            "<code>Caustikon</code> — математика: преломление, Френель, модели дисперсии. <code>Caustikon.Glasses</code> — каталог с поглощением, температурой и цветом. Оба под .NET 8 и .NET 10 без зависимостей вне базовой библиотеки классов. Исходники, issues и данные — на <a href=\"https://github.com/levvs-one/caustikon\" rel=\"noopener\">GitHub</a>, лицензия MIT."),
        ["about.cite.h"] = ("Citing", "Как ссылаться"),
        ["about.cite.p"] = ("For the glass data cite M. N. Polyanskiy, \"Refractiveindex.info database of optical constants\", <em>Scientific Data</em> 11, 94 (2024), and the manufacturer catalog named in the glass's provenance. For the code cite the repository and the version shown in the footer.",
            "На данные стёкол ссылайся так: M. N. Polyanskiy, «Refractiveindex.info database of optical constants», <em>Scientific Data</em> 11, 94 (2024), плюс каталог производителя, названный в происхождении стекла. На код — репозиторий и версия из подвала."),
    };
}
